include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declarations: false
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    avoid_print: true
    prefer_final_locals: true

analyzer:
  errors:
    deprecated_member_use: info
  exclude:
    - "**/*.g.dart"
    - "build/**"
